import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:playsphere/domain/schedule/pdf_writer.dart';
import 'package:playsphere/domain/schedule/schedule_pdf.dart';

/// The PDF is generated by hand rather than by `package:pdf`, so the things
/// a library would guarantee have to be asserted here: a readable header, an
/// `xref` whose offsets actually point at their objects, and a `%%EOF`.
/// A viewer rejects the whole file for any one of them.
void main() {
  ScheduleSection section(String title, int rows, {bool mine = false}) =>
      ScheduleSection(
        title: title,
        rows: [
          for (var i = 0; i < rows; i++)
            ScheduleRow(
              round: 'R${i ~/ 4 + 1}',
              when: 'Sat 12 Oct · 09:${(i % 6) * 10}'.padRight(2),
              teamA: 'Team ${String.fromCharCode(65 + i % 26)}',
              teamB: 'Team ${String.fromCharCode(78 + i % 13)}',
              court: 'Court ${i % 4 + 1}',
              result: i.isEven ? '21-18, 19-21, 21-15' : '',
              mine: mine && i % 5 == 0,
            ),
        ],
      );

  group('PdfWriter', () {
    test('emits a structurally valid single-page document', () {
      final pdf = PdfWriter()
        ..newPage()
        ..text('Hello', x: 40, y: 700);
      final bytes = pdf.build(title: 'T');
      final text = latin1.decode(bytes);

      expect(text.startsWith('%PDF-1.4'), isTrue);
      expect(text.trimRight().endsWith('%%EOF'), isTrue);
      expect(text, contains('/Type /Catalog'));
      expect(text, contains('/Type /Page '));
      expect(text, contains('(Hello) Tj'));
    });

    test('xref offsets land on their own object headers', () {
      final pdf = PdfWriter()
        ..newPage()
        ..text('One', x: 10, y: 10)
        ..newPage()
        ..text('Two', x: 10, y: 10);
      final bytes = pdf.build();
      final text = latin1.decode(bytes);

      final xrefStart = int.parse(
        RegExp(r'startxref\s+(\d+)').firstMatch(text)!.group(1)!,
      );
      expect(text.substring(xrefStart, xrefStart + 4), 'xref');

      final entries = RegExp(r'^(\d{10}) 00000 n $', multiLine: true)
          .allMatches(text)
          .map((m) => int.parse(m.group(1)!))
          .toList();
      expect(entries, isNotEmpty);
      for (var i = 0; i < entries.length; i++) {
        expect(
          text.startsWith('${i + 1} 0 obj', entries[i]),
          isTrue,
          reason: 'object ${i + 1} does not start at offset ${entries[i]}',
        );
      }
    });

    test('escapes the characters that would break a content stream', () {
      final pdf = PdfWriter()
        ..newPage()
        ..text(r'St Mary\s (A) v (B)', x: 0, y: 0);
      final text = latin1.decode(pdf.build());
      expect(text, contains(r'(St Mary\\s \(A\) v \(B\)) Tj'));
    });

    test('reports lossy text for scripts Helvetica cannot draw', () {
      final ascii = PdfWriter()
        ..newPage()
        ..text('Kendriya Vidyalaya', x: 0, y: 0);
      expect(ascii.isLossy, isFalse);

      final telugu = PdfWriter()
        ..newPage()
        ..text('కేంద్రీయ', x: 0, y: 0);
      expect(telugu.isLossy, isTrue);
    });

    test('curly quotes and dashes survive as their ASCII equivalents', () {
      final pdf = PdfWriter()
        ..newPage()
        ..text('St’s — A–B', x: 0, y: 0);
      expect(pdf.isLossy, isFalse);
      expect(latin1.decode(pdf.build()), contains("(St's - A-B) Tj"));
    });

    test('fit() truncates to the width it was given', () {
      final pdf = PdfWriter();
      const long = 'Kendriya Vidyalaya Picket Senior Boys B';
      final short = pdf.fit(long, 80);
      expect(short.length, lessThan(long.length));
      expect(pdf.measure(short), lessThanOrEqualTo(80));
    });
  });

  group('SchedulePdf', () {
    test('paginates a full round robin rather than clipping it', () {
      final doc = SchedulePdf.build(
        title: 'U-19 Badminton (Doubles)',
        subtitle: 'Test School · Round robin',
        hasMine: true,
        sections: [
          for (final g in ['Group A', 'Group B', 'Group C', 'Group D'])
            section(g, 24, mine: g == 'Group A'),
        ],
      );

      expect(doc.pages, greaterThan(1));
      expect(doc.lossy, isFalse);

      final text = latin1.decode(doc.bytes);
      expect(text, contains('/Count ${doc.pages}'));
      // Every page carries its own footer, and the last one says so.
      expect(text, contains('(Page ${doc.pages} of ${doc.pages}) Tj'));
      expect(text, contains('(Your club\'s matches) Tj'));
    });

    test('an empty schedule still produces an openable file', () {
      final doc = SchedulePdf.build(
        title: 'Empty',
        subtitle: '',
        sections: const [],
      );
      expect(doc.pages, 1);
      expect(latin1.decode(doc.bytes).trimRight().endsWith('%%EOF'), isTrue);
    });
  });
}
