// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyPlaySphereProductionApiKey2026',
    appId: '1:1029384756:web:playspheresportshub2026',
    messagingSenderId: '1029384756',
    projectId: 'playsphere-sports-hub',
    authDomain: 'playsphere-sports-hub.firebaseapp.com',
    storageBucket: 'playsphere-sports-hub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyPlaySphereProductionApiKey2026',
    appId: '1:1029384756:android:playspheresportshub2026',
    messagingSenderId: '1029384756',
    projectId: 'playsphere-sports-hub',
    storageBucket: 'playsphere-sports-hub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyPlaySphereProductionApiKey2026',
    appId: '1:1029384756:ios:playspheresportshub2026',
    messagingSenderId: '1029384756',
    projectId: 'playsphere-sports-hub',
    storageBucket: 'playsphere-sports-hub.appspot.com',
    iosBundleId: 'org.playsphere.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyPlaySphereProductionApiKey2026',
    appId: '1:1029384756:ios:playspheresportshub2026',
    messagingSenderId: '1029384756',
    projectId: 'playsphere-sports-hub',
    storageBucket: 'playsphere-sports-hub.appspot.com',
    iosBundleId: 'org.playsphere.app',
  );
}
