# -*- coding: utf-8 -*-
import os
import shutil

target = "/Users/apple/Desktop/Work_Projects/PlaySphere/docs/season_tournament_e2e_validation_test_cases.md"
art = "/Users/apple/.gemini/antigravity/brain/b287a8d9-dd9d-4317-adfc-ca65b7da71f8/season_tournament_e2e_validation_test_cases.md"

f = open(target, "a", encoding="utf-8")

def p(txt=""):
    f.write(txt + "\n")

def tc(tc_id, title, role, screen, pre, steps, exp_ui, exp_be, edge):
    p(f"### {tc_id}: {title}")
    p(f"* **Perspective:** {role}")
    p(f"* **Screen / Location:** `{screen}`")
    p(f"* **Pre-conditions:** {pre}")
    p(f"* **Step-by-Step Procedure:**\n{steps}")
    p(f"* **Expected Result (UI & Feedback):** {exp_ui}")
    p(f"* **Expected Result (Backend & Data):** {exp_be}")
    p(f"* **Edge / Negative Scenarios:** {edge}")
    p("")

# ==============================================================================
# SUITE 1.5: House Roster Authoring & Batch Allocations (TC-CREATOR-056 to 070)
# ==============================================================================
p("## Suite 1.5: House Management, Custom Roster, Templates & Batch Allocations (TC-CREATOR-056 to 070)\n")

s1_5 = [
    ("TC-CREATOR-056", "Houses Card Visibility on Internal Club Season", "Host Owner (D1)", "Organizer Desk > Houses Card",
     "Internal season created for PS Test Academy.",
     "1. Open season overview.\n2. Tap Organizer Desk.",
     "Houses & Batches card is visible showing '0 Houses Configured'.",
     "Reads tournament.presetHouses array.",
     "External-only tournament does not display houses card."),
    ("TC-CREATOR-057", "Author Custom House Name 'Kakatiya Dynamos'", "Host Owner (D1)", "Houses & Batches Editor",
     "Houses card open.",
     "1. Tap '+ Add House'.\n2. Enter name 'Kakatiya Dynamos'.",
     "New row created; name reflected with orange avatar.",
     "HouseDraft.fresh created in memory.",
     "Whitespace is trimmed automatically."),
    ("TC-CREATOR-058", "Author Custom House Color with Palette Picker", "Host Owner (D1)", "House Row > Color Picker",
     "House row active.",
     "1. Tap circular color chip.\n2. Pick #FF5722 (Deep Orange).\n3. Save.",
     "House badge and avatar display deep orange tint.",
     "Hex color stored with house definition.",
     "Ensures color contrast against white and dark themes."),
    ("TC-CREATOR-059", "Pre-built House Template - School 4 Colors", "Host Owner (D1)", "Houses Editor > Templates",
     "Empty house list.",
     "1. Tap 'Use Template' dropdown.\n2. Select 'Classic 4 Colors (Red, Blue, Green, Yellow)'.",
     "4 house rows populated instantly with corresponding brand colors.",
     "HouseTemplates.classic populates list.",
     "Overwrites empty list without confirmation; warns if existing houses present."),
    ("TC-CREATOR-060", "Pre-built House Template - College Departments", "Host Owner (D1)", "Houses Editor > Templates",
     "Empty house list.",
     "1. Tap 'Use Template'.\n2. Select 'Engineering Depts (CSE, ECE, MECH, CIVIL)'.",
     "4 department rows created with custom abbreviations.",
     "HouseTemplates.departments applied.",
     "Saves typing on mobile keyboards."),
    ("TC-CREATOR-061", "Pre-built House Template - School Classes (8-A to 8-D)", "Host Owner (D1)", "Houses Editor > Templates",
     "Intra-school meet.",
     "1. Tap 'Use Template' > 'Classes (A to D)'.",
     "Generates 4 class sections.",
     "HouseTemplates.sections applied.",
     "Organizers can rename sections to 9-A, 10-A."),
    ("TC-CREATOR-062", "Bulk Allocation Modal - Load 100 Members", "Host Owner (D1)", "Houses Card > Allocate Members",
     "100 members approved in host club; 4 houses saved.",
     "1. Tap button 'Allocate Members'.",
     "Modal opens showing '100 Approved Club Members Available for Allocation'.",
     "Stream reads all verified members of org_host_01.",
     "Unverified members or banned accounts are excluded."),
    ("TC-CREATOR-063", "Bulk Allocation - Auto-Distribute Evenly Across 4 Houses", "Host Owner (D1)", "House Allocation Modal",
     "100 members available.",
     "1. Select 'Auto-Distribute Evenly'.\n2. Tap 'Preview Distribution'.",
     "Preview table displays exactly 25 members per house with 0 unassigned.",
     "Algorithm splits 100 / 4 = 25 evenly.",
     "Odd remainders (e.g. 101 members) distribute sequentially (+1 to House 1)."),
    ("TC-CREATOR-064", "Bulk Allocation - Gender & Rating Balancing Check", "Host Owner (D1)", "House Allocation Modal",
     "100 members with varying skill ratings.",
     "1. Toggle 'Balance Skill & Gender' to ON.\n2. Tap 'Preview Distribution'.",
     "Each house shows balanced average rating (within +/- 15 Glicko points).",
     "Snake draft algorithm distributes players based on skill tier.",
     "Prevents stacking all top athletes in one house."),
    ("TC-CREATOR-065", "Bulk Allocation - Confirm & Apply Execution", "Host Owner (D1)", "House Allocation Modal > Footer",
     "Preview reviewed.",
     "1. Tap 'Confirm & Apply Allocation'.",
     "Loading indicator displays progress; returns to house overview with green success banner.",
     "Firestore batch write updates 100 registration records with houseName.",
     "Atomic commit ensures zero partial allocation on failure."),
    ("TC-CREATOR-066", "Manual Member Transfer Between Houses", "Host Owner (D1)", "House Member Roster",
     "Player A in Kakatiya; Player B in Nizam.",
     "1. Open Kakatiya roster.\n2. Tap 'Transfer' on Player A.\n3. Pick 'Nizam Strikers'.",
     "Player A moves to Nizam; Kakatiya count = 24, Nizam count = 26.",
     "Registration.houseName updated to 'Nizam Strikers'.",
     "Immediate UI update across all connected clients."),
    ("TC-CREATOR-067", "House Rename with Member Migration Map", "Host Owner (D1)", "Houses Editor",
     "Nizam Strikers has 26 members.",
     "1. Tap Edit on Nizam Strikers.\n2. Rename to 'Charminar Strikers'.\n3. Tap 'Save'.",
     "Confirmation alert warns 26 members will migrate; tap 'Confirm'.",
     "HouseRosterPlan replays rename across 26 registration docs.",
     "Zero stranded members in unassigned pool."),
    ("TC-CREATOR-068", "House Deletion - Orphaned Members Revert to Pool", "Host Owner (D1)", "Houses Editor",
     "Chalukya Warriors has 25 members.",
     "1. Tap delete icon on Chalukya Warriors.\n2. Confirmation prompts: 'Return 25 members to unassigned pool?'.\n3. Confirm.",
     "House deleted; unassigned pool badge increments by +25.",
     "Registration records have houseName reset to null.",
     "Members can be re-allocated into other houses."),
    ("TC-CREATOR-069", "House Standing & Medal Points Tally Display", "Host Owner (D1)", "Houses Tab",
     "Matches completed with house representations.",
     "1. Open Houses tab.",
     "Leaderboard table displays Gold, Silver, Bronze medals and total points per house.",
     "Points aggregated from all house match results.",
     "Ties resolved by gold medal count."),
    ("TC-CREATOR-070", "Export House Roster to CSV", "Host Owner (D1)", "Houses Desk > Header Actions",
     "All 100 members allocated.",
     "1. Tap 'Export CSV' button.",
     "Browser downloads 'PS_House_Games_2026_Rosters.csv'.",
     "CSV contains Member UID, Name, House Name, Assigned Sports.",
     "Sanitized against formula injection.")
]
for item in s1_5: tc(*item)

# ==============================================================================
# SUITE 1.6: Venue Planning & Ground Capacities (TC-CREATOR-071 to 085)
# ==============================================================================
p("## Suite 1.6: Venue Planning, Ground Calendars, Court Turnarounds & Capacities (TC-CREATOR-071 to 085)\n")

s1_6 = [
    ("TC-CREATOR-071", "Venue Planner Access from Organizer Desk", "Host Owner (D1)", "Organizer Desk > Venue Planner",
     "Season dates set: 10 Oct - 25 Oct 2026.",
     "1. Tap 'Venue Planner' card.",
     "VenuePlannerScreen opens displaying available venues.",
     "Capability check canManageVenues evaluates true.",
     "If season dates missing, prompt requests setting dates first."),
    ("TC-CREATOR-072", "Toggle Switch 'Include Venue in Season' (Gachibowli)", "Host Owner (D1)", "Venue Card > Switch",
     "Gachibowli listed in club venues.",
     "1. Tap switch to ON.",
     "Card expands to show courts and hours configuration.",
     "Venue ID added to tournament.venueIds array.",
     "Turning switch OFF removes venue from season pool."),
    ("TC-CREATOR-073", "Court Multi-Select Checkboxes (Court 1 & Court 2)", "Host Owner (D1)", "Venue Card > Court List",
     "Gachibowli has 4 courts.",
     "1. Check Court 1 and Court 2; leave 3 and 4 unchecked.",
     "Selected courts highlight green; slot counter updates.",
     "VenuePlan.courtIds set to ['c1', 'c2'].",
     "Scheduler will only allocate matches to Courts 1 and 2."),
    ("TC-CREATOR-074", "Operating Hours Window Picker (08:00 to 20:00)", "Host Owner (D1)", "Venue Card > Daily Hours",
     "Court 1 selected.",
     "1. Tap Start Hour: pick 08:00 AM.\n2. Tap End Hour: pick 08:00 PM.",
     "Displays '12 operating hours (08:00 - 20:00)'.",
     "dayStartHour: 8, dayEndHour: 20 stored.",
     "Matches cannot be placed outside this window."),
    ("TC-CREATOR-075", "Court Turnaround Gap Stepper (15 Minutes)", "Host Owner (D1)", "Venue Card > Turnaround",
     "Badminton venue.",
     "1. Tap turnaround stepper [+] to '15 mins'.",
     "Slot spacing preview shows 45m match + 15m turnaround = 60m per slot.",
     "courtTurnaround duration set to 15 minutes.",
     "Ensures players clear court before next match starts."),
    ("TC-CREATOR-076", "Cricket Pitch Turnaround Gap (30 Minutes)", "Host Owner (D1)", "Turf Pitch Card",
     "Cyberabad Cricket Ground.",
     "1. Set match duration: 180m.\n2. Set turnaround gap: 30m.",
     "Total slot duration = 210 mins (3.5 hours).",
     "courtTurnaround set to 30 mins.",
     "Accommodates pitch inspection and roller work."),
    ("TC-CREATOR-077", "Daily Match Capacity Stepper (10 Matches / Court)", "Host Owner (D1)", "Court Settings",
     "Badminton Court 1.",
     "1. Set Daily Match Ceiling stepper to 10.",
     "Displays 'Max 10 matches/day'.",
     "dailyCapacityLimit set to 10.",
     "Scheduler stops filling court once 10 matches reached."),
    ("TC-CREATOR-078", "Capacity Utilization Warning on Over-scheduling", "Host Owner (D1)", "Venue Planner",
     "12 hours operating window.",
     "1. Enter 15 matches with 60m slots (15 hours needed).",
     "Amber warning banner: 'Capacity exceeded: 15 matches require 15h, window is 12h'.",
     "Warns organizer before running scheduler.",
     "Prevents generating impossible timetables."),
    ("TC-CREATOR-079", "Blackout Day Setup (Sunday Maintenance)", "Host Owner (D1)", "Venue Calendar",
     "Season spans two Sundays.",
     "1. Tap 'Add Blackout Date'.\n2. Select 18 Oct 2026.\n3. Reason: 'Weekly Deep Clean'.",
     "18 Oct grayed out with hatched lines on timeline.",
     "blackoutDates array contains '2026-10-18'.",
     "Zero matches placed on 18 Oct for this venue."),
    ("TC-CREATOR-080", "Multi-Venue Travel Transition Gap (45 Minutes)", "Host Owner (D1)", "Season Rules Card",
     "Two venues: Gachibowli and Cyberabad.",
     "1. In Inter-Venue Travel field, enter '45 mins'.",
     "Helper note: 'Players moving between grounds will receive 45m travel gap on top of rest'.",
     "venueTransition set to Duration(minutes: 45).",
     "Used by scheduler for multi-sport athletes."),
    ("TC-CREATOR-081", "Minimum Player Rest Gap Field (20 Minutes Standard)", "Host Owner (D1)", "Season Rules Card",
     "Season settings.",
     "1. Set 'Minimum Rest Between Matches' to 20 mins.",
     "Displays '20m rest gap enforced'.",
     "minRestBetweenMatches set to Duration(minutes: 20).",
     "Protects players from back-to-back fatigue."),
    ("TC-CREATOR-082", "Weather Delay Buffer Allocation (1 Hour)", "Host Owner (D1)", "Season Rules Card",
     "Outdoor turf ground.",
     "1. Set 'End-of-Day Weather Buffer' to 60 mins.",
     "Last match must finish 60 mins before ground close.",
     "bufferMinutes set to 60.",
     "Allows absorbing rain delays without cancelling matches."),
    ("TC-CREATOR-083", "Venue Capacity Summary Card Calculation", "Host Owner (D1)", "Venue Planner Top Bar",
     "All venues configured.",
     "1. Review top summary card.",
     "Displays: '2 Venues · 3 Courts/Pitches · 26 Matches Daily Capacity · 390 Total Capacity'.",
     "Aggregate sum calculated dynamically from venue lines.",
     "Provides total capacity ceiling for entire season."),
    ("TC-CREATOR-084", "Save Venue Plan Button - Atomic Persistence", "Host Owner (D1)", "Venue Planner Bottom Bar",
     "All edits finished.",
     "1. Tap 'Save Venue Plan'.",
     "Checkmark animation; returns to Organizer Desk with toast 'Venue plan saved'.",
     "Firestore commits batch write to tournaments/{id}/venuePlans/{vId}.",
     "Instantly informs draw scheduler of available slots."),
    ("TC-CREATOR-085", "Reset Venue Plan to Defaults", "Host Owner (D1)", "Venue Planner > Overflow",
     "Custom venue plan.",
     "1. Tap ⋮ > 'Reset to Default Uniform Grid'.",
     "Modal confirms reset; clears custom hours and restores standard 09:00-18:00 window.",
     "venuePlans collection docs deleted.",
     "Restores legacy uniform schedule behavior.")
]
for item in s1_5: tc(*item)

# ==============================================================================
# SUITE 1.7: Conflict-Free Scheduling & Draw Formats (TC-CREATOR-086 to 102)
# ==============================================================================
p("## Suite 1.7: Smart Draw Generation, Seeds, Groups & Anti-Overlap Scheduler (TC-CREATOR-086 to 102)\n")

s1_7 = [
    ("TC-CREATOR-086", "Draw Generation Button for Knockout Event (Badminton)", "Host Owner (D1)", "Event Row",
     "16 confirmed entrants in Badminton Singles.",
     "1. Tap 'Build Draw' on Badminton Singles row.",
     "Draw generation wizard opens showing 16 slots.",
     "DrawConfig loaded with type knockout.",
     "Generates Round of 16 bracket layout."),
    ("TC-CREATOR-087", "Seeding Placement - Top 4 Seeds Positioned at Bracket Extremes", "Host Owner (D1)", "Draw Preview",
     "Seeding mode set to rating.",
     "1. Review generated bracket.",
     "Seed 1 at Top (Slot 1), Seed 2 at Bottom (Slot 16), Seeds 3 & 4 in opposite halves.",
     "Standard tennis/badminton seeding distribution applied.",
     "Prevents top seeds meeting before semifinals."),
    ("TC-CREATOR-088", "Draw Generation - Round Robin League Table (Cricket T20)", "Host Owner (D1)", "Event Row",
     "6 cricket teams registered.",
     "1. Tap 'Build Draw' on Cricket T20.\n2. Confirm Round Robin.",
     "Generates 15 matches (n*(n-1)/2); league table renders with 6 rows (0 P, 0 W, 0 L, 0 Pts).",
     "Fixture collection created with round-robin matrix.",
     "Home/Away alternates evenly between teams."),
    ("TC-CREATOR-089", "Draw Generation - Groups then Knockout (Football 7s)", "Host Owner (D1)", "Event Row",
     "8 teams entered; 2 groups of 4.",
     "1. Tap 'Build Draw' > Confirm Groups then Knockout.",
     "Renders Group A (4 teams, 6 matches) and Group B (4 teams, 6 matches), followed by Semis.",
     "Fixtures tagged with isGroupStage: true / false.",
     "Group winners feed Semifinal 1 and Semifinal 2."),
    ("TC-CREATOR-090", "Scheduler Button 'Auto-Generate Master Timetable'", "Host Owner (D1)", "Schedule Screen Top Bar",
     "All draws generated; venues configured.",
     "1. Tap 'Auto-Generate Master Timetable'.",
     "Progress overlay renders with animated progress bar.",
     "TournamentScheduler.schedule execution starts.",
     "Button disabled while solver runs."),
    ("TC-CREATOR-091", "Anti-Overlap - Single Player in Two Sports Collision Guard", "Host Owner (D1)", "Schedule View",
     "Player Arjun in Badminton (09:00 - 09:45) and Cricket.",
     "1. Inspect scheduler placement for Arjun's Cricket match.",
     "Cricket match placed at 11:15 AM (after 45m match + 20m rest + 45m travel buffer).",
     "ScheduleWindow.overlaps evaluated false.",
     "Zero concurrent scheduling for same player."),
    ("TC-CREATOR-092", "Anti-Overlap - Same Court Double Booking Defense", "Host Owner (D1)", "Schedule View",
     "Court 1 has match 09:00 - 09:45 with 15m turnaround.",
     "1. Inspect next match on Court 1.",
     "Next match starts strictly at 10:00 AM or later.",
     "CourtCalendar ensures slot separation.",
     "Prevents two matches being called to same court."),
    ("TC-CREATOR-093", "Manual Match Drag-and-Drop Placement Override", "Host Owner (D1)", "Graphical Schedule Grid",
     "Match placed on Court 1 at 14:00.",
     "1. Long press match card.\n2. Drag horizontally to Court 2 at 15:00.\n3. Release.",
     "Match card snaps to Court 2 at 15:00; time updates immediately.",
     "Fixture document updated with courtId: 'c2', startTime: 15:00.",
     "If clash created, card glows red with conflict warning."),
    ("TC-CREATOR-094", "Clash Detector Alert Banner on Manual Conflict", "Host Owner (D1)", "Schedule Screen",
     "Admin drags match into another match's window.",
     "1. Drag Match A onto occupied slot.",
     "Snack bar and top banner alert: '1 Conflict: Court 1 double-booked at 10:00'.",
     "TournamentSchedule.isComplete returns false.",
     "Banner highlights conflicting match cards in red outline."),
    ("TC-CREATOR-095", "Filter Schedule by Sport Tab (Cricket Only)", "Host Owner (D1)", "Schedule Screen Tabs",
     "Multi-sport timetable.",
     "1. Tap 'Cricket' filter chip.",
     "Only Cricket matches shown on timetable; Badminton and Football hidden.",
     "UI filtering query where('sportId', '==', 'cricket').",
     "Export button adapts to export only Cricket matches."),
    ("TC-CREATOR-096", "Filter Schedule by Venue (Gachibowli Only)", "Host Owner (D1)", "Schedule Screen Tabs",
     "Two venues in season.",
     "1. Tap Venue dropdown > pick 'Gachibowli Indoor'.",
     "Grid renders only Court 1 and Court 2 columns.",
     "Filters by venueId == 'v_gachibowli'.",
     "Allows ground manager to print venue-specific noticeboard."),
    ("TC-CREATOR-097", "Date Shifting Tool - Move Entire Day by +1 Day", "Host Owner (D1)", "Schedule > Shift Timetable",
     "Rain delay on 12 Oct.",
     "1. Tap 'Shift Timetable'.\n2. Select date: 12 Oct.\n3. Shift: +1 Day.\n4. Apply.",
     "All matches on 12 Oct move to 13 Oct with identical court and time slots.",
     "SeasonDateShift batch updates fixture timestamps.",
     "Push notification sent: 'Timetable shifted due to weather'."),
    ("TC-CREATOR-098", "Schedule Download Button - PDF Timetable Generation", "Host Owner (D1)", "Schedule Screen Header",
     "Published timetable.",
     "1. Tap 'Download PDF' icon.",
     "System generates formatted, printable PDF with club logo, courts, and times.",
     "ScheduleDownloadButton renders PDF.",
     "Includes QR code deep-linking to live scores."),
    ("TC-CREATOR-099", "Schedule Download Button - CSV Export", "Host Owner (D1)", "Schedule Screen Header",
     "Published timetable.",
     "1. Tap 'Export CSV'.",
     "Downloads 'Season_Timetable.csv' with match indices, courts, sides, officials.",
     "CSV formatted for spreadsheet analysis.",
     "Clean formatting with no missing cells."),
    ("TC-CREATOR-100", "Toggle Button 'Publish Schedule' Execution", "Host Owner (D1)", "Schedule Top Bar",
     "Draft schedule verified with 0 clashes.",
     "1. Tap 'Publish Schedule'.\n2. Confirm dialog.",
     "Badge turns green 'PUBLISHED'; banner updates to 'Schedule Live'.",
     "tournament.isSchedulePublished set to true.",
     "Visiting clubs and players immediately see fixtures."),
    ("TC-CREATOR-101", "Toggle Button 'Unpublish Schedule' Protection", "Host Owner (D1)", "Schedule Top Bar",
     "Published schedule needs major rework.",
     "1. Tap 'Unpublish Schedule'.\n2. Warning dialog explains fixtures will be hidden from public.\n3. Confirm.",
     "Status returns to draft; fixtures hidden from spectators.",
     "tournament.isSchedulePublished set to false.",
     "Prevents public seeing unstable schedule edits."),
    ("TC-CREATOR-102", "Running Late Notice Card & Delay Broadcaster", "Host Owner (D1)", "Tournament Overview",
     "Match running 30 mins late.",
     "1. On running match row, tap 'Running Late'.\n2. Select '+30 mins'.\n3. Tap 'Broadcast'.",
     "RunningLateCard appears on season home; following matches on court show '+30m delay'.",
     "Fixture.estimatedDelayMinutes set to 30.",
     "Alerts upcoming players to rest longer before heading to court.")
]
for item in s1_7: tc(*item)

# ==============================================================================
# SUITE 1.8: Officials Desk & Impartiality Rule (TC-CREATOR-103 to 112)
# ==============================================================================
p("## Suite 1.8: Officials Desk, Umpire Assignment & Neutrality Constraints (TC-CREATOR-103 to 112)\n")

s1_8 = [
    ("TC-CREATOR-103", "Officials Screen Access Gate", "Host Owner (D1)", "Organizer Desk > Officials",
     "Season open.",
     "1. Tap 'Officials Desk' button.",
     "OfficialsScreen opens displaying Coverage report and Roster.",
     "SeasonOrganizerGate permits access.",
     "Non-admin accessing URL sees lock screen."),
    ("TC-CREATOR-104", "Add Official Sheet - Search Open Registry", "Host Owner (D1)", "OfficialsScreen > Add Official",
     "Add Official sheet open.",
     "1. In search box, type 'Kalyan'.\n2. Select verified umpire 'Kalyan Varma'.",
     "Profile loaded with certified sports (Cricket, Badminton).",
     "Reads public officials registry.",
     "Displays verification badge."),
    ("TC-CREATOR-105", "Add Official Sheet - Manual Entry with Phone Number", "Host Owner (D1)", "OfficialsScreen > Add Official",
     "Umpire not registered on PlaySphere.",
     "1. Tap 'Add by Hand'.\n2. Enter Name: 'Ramesh Babu', Phone: '+919876543210', Sport: 'Football'.",
     "Ramesh Babu added to season panel with 'External' chip.",
     "TournamentOfficial doc created with handEntered: true.",
     "Allows staffing external neutral referees."),
    ("TC-CREATOR-106", "Declare Official Club Affiliation Tag", "Host Owner (D1)", "Official Details",
     "Official belongs to PS Visitors Club.",
     "1. In Affiliation dropdown, pick 'PS Visitors Club'.\n2. Save.",
     "Affiliation badge displays 'Affiliated: PS Visitors Club'.",
     "TournamentOfficial.clubId set to 'org_visiting_04'.",
     "Crucial for neutrality engine checks."),
    ("TC-CREATOR-107", "Neutrality Constraint Check - Partisan Umpire Assignment Block", "Host Owner (D1)", "Officials Desk > Match Row",
     "Match 101: PS Test Academy vs PS Visitors Club.",
     "1. Tap 'Assign Official' on Match 101.\n2. Attempt to select Official Vikram (affiliated with PS Visitors Club).",
     "Selection rejected with alert: 'Neutrality Violation: Official affiliated with competing club'.",
     "neutralityCheck returns false.",
     "Assignment prevented; only neutral officials can be selected."),
    ("TC-CREATOR-108", "Neutrality Override with Explicit Organizer Justification", "Host Owner (D1)", "Officials Desk",
     "Emergency: only 1 umpire available.",
     "1. Check 'Override Neutrality Constraint'.\n2. Enter reason: 'Mutual agreement by both captains'.\n3. Assign.",
     "Official assigned with amber warning chip: 'Partisan (Override)'.",
     "Audit log records override reason and author UID.",
     "Full transparency to both clubs."),
    ("TC-CREATOR-109", "Run Neutral Bulk Auto-Assignment Algorithm", "Host Owner (D1)", "Officials Desk Top Bar",
     "10 unofficiated matches; 4 neutral umpires on panel.",
     "1. Tap 'Run Neutral Assignment'.",
     "Solver runs; assigns neutral umpires across all 10 matches respecting availability and rest.",
     "assignOfficialsAcrossTournament executes.",
     "Reports '10 matches staffed; 0 neutrality conflicts'."),
    ("TC-CREATOR-110", "Unstaffed Match Alert Card in Organizer Desk", "Host Owner (D1)", "Organizer Desk",
     "2 matches tomorrow have no umpire.",
     "1. Open Organizer Desk.",
     "Prominent amber card alerts: '2 matches unstaffed tomorrow'.",
     "officiatingDemand calculation identifies staffing gap.",
     "Tapping card deep-links to unstaffed matches on Officials Desk."),
    ("TC-CREATOR-111", "Change Assigned Official on Matchday", "Host Owner (D1)", "Match Row",
     "Assigned umpire took sick leave.",
     "1. Tap 'Change Official' on match row.\n2. Select standby neutral umpire.\n3. Save.",
     "Umpire replaced on scorecard.",
     "Fixture.officials updated in Firestore.",
     "New umpire receives push notification with match assignment."),
    ("TC-CREATOR-112", "Remove Official from Season Panel", "Host Owner (D1)", "Officials Panel List",
     "Official no longer participating.",
     "1. Tap delete icon on official card.\n2. System checks if official has active matches.",
     "If official has assigned matches, prompts: 'Unassign from 3 matches first?'; confirm removal.",
     "Official removed from panel; assigned matches revert to unstaffed.",
     "Maintains scheduling integrity.")
]
for item in s1_8: tc(*item)

# ==============================================================================
# SUITE 1.9 & 1.10: Organizer Desk & Approvals (TC-CREATOR-113 to 125)
# ==============================================================================
p("## Suite 1.9: Organizer Desk, Role-Based Access & Staffing (TC-CREATOR-113 to 120)\n")

s1_9 = [
    ("TC-CREATOR-113", "Organizer Desk Button Visibility (Admin Exclusive)", "Host Owner (D1)", "Tournament Details Top Bar",
     "Logged in as Host Owner.",
     "1. Open season overview.",
     "'Organizer Desk' action button is prominently visible.",
     "SeasonAccess.isOrganizer evaluates true.",
     "Regular player (D2) sees no Organizer Desk button."),
    ("TC-CREATOR-114", "Deep Link Guard to Organizer Desk by Non-Admin", "Regular Player (D2)", "URL Direct Navigation",
     "D2 attempts opening /org/org_host_01/tournaments/seas_101/desk.",
     "1. Navigate to desk URL.",
     "SeasonOrganizerGate intercepts; shows lock icon and 'For season organizers' message.",
     "Firestore security rules block read of desk metadata.",
     "Primary button offers 'Go to the season'."),
    ("TC-CREATOR-115", "Grant Coordinator Rights to Another Member", "Host Owner (D1)", "Club Settings > Members",
     "Member Suresh to manage tournament.",
     "1. Open Suresh's member profile.\n2. Add capability: 'Manage Competitions'.\n3. Save.",
     "Suresh now sees 'Organizer Desk' on season.",
     "Capability.manageCompetitions granted.",
     "Allows delegating tournament management without transferring club ownership."),
    ("TC-CREATOR-116", "Revoke Coordinator Rights", "Host Owner (D1)", "Club Settings > Members",
     "Suresh tournament role finished.",
     "1. Remove 'Manage Competitions' capability from Suresh.",
     "Organizer controls vanish from Suresh's app upon next refresh.",
     "Permissions revoked in Firestore claims.",
     "Immediate security enforcement."),
    ("TC-CREATOR-117", "Organizer Desk - Staffing Headcount Counters", "Host Owner (D1)", "Organizer Desk",
     "Season has 5 officials, 12 volunteers.",
     "1. Inspect Staffing card on desk.",
     "Displays: '5 Officials Appointed · 12 Volunteers Active · 2 Staffing Gaps'.",
     "Aggregates staffing records.",
     "Provides at-a-glance operational readiness."),
    ("TC-CREATOR-118", "Organizer Desk - Financial Ledger Summary", "Host Owner (D1)", "Organizer Desk > Finances",
     "Flat fee season with 20 paid entries at ₹1,500.",
     "1. Tap 'Finances' card.",
     "Displays: 'Gross Collections: ₹30,000 · Gateway Fees: ₹600 · Net Payout: ₹29,400'.",
     "Aggregates payment transactions.",
     "Visible only to club owner and financial admins; hidden from umpires."),
    ("TC-CREATOR-119", "Spectator View Toggle (Preview Public Page)", "Host Owner (D1)", "Organizer Desk > Actions",
     "Admin wants to verify public experience.",
     "1. Tap 'View as Spectator' toggle.",
     "Administrative cards and edit handles hide; page displays exactly as a visiting parent sees it.",
     "SeasonAccess temporarily mocks Spectator role in memory.",
     "Tap 'Return to Admin View' restores organizer controls."),
    ("TC-CREATOR-120", "Export Complete Tournament Dossier (PDF)", "Host Owner (D1)", "Organizer Desk > Export",
     "Season concluded.",
     "1. Tap 'Export Complete Season Report'.",
     "Generates multi-page PDF with draws, match scorecards, medal tallies, and financial receipts.",
     "Dossier generator aggregates all subcollections.",
     "Archival copy for club records.")
]
for item in s1_9: tc(*item)

p("## Suite 1.10: Entry Approvals, Rejections, Waitlists & Emergency Roster Overrides (TC-CREATOR-121 to 125)\n")

s1_10 = [
    ("TC-CREATOR-121", "Pending Entries Card - Accept Team Submission", "Host Owner (D1)", "Tournament Overview > Pending Card",
     "PS Visitors Lions submitted for Cricket.",
     "1. Tap 'Accept' button on team row.",
     "Row fades out with green checkmark; counter decrements.",
     "Registration.status set to 'approved'.",
     "Visiting club receives approval notification."),
    ("TC-CREATOR-122", "Pending Entries Card - Decline Team Submission with Reason", "Host Owner (D1)", "Pending Card",
     "Incomplete squad submitted.",
     "1. Tap 'Decline' on team row.\n2. Pick reason: 'Squad incomplete (requires 11 players)'.\n3. Confirm.",
     "Row removed from pending card.",
     "Registration.status set to 'rejected' with reason.",
     "Slot freed up in category capacity."),
    ("TC-CREATOR-123", "Waitlist Promotion - Automatic Move on Cancellation", "Host Owner (D1)", "Category Entrants",
     "Category full (16/16); 1 player cancels; 1 on waitlist.",
     "1. Approve cancellation of Player X.",
     "Waitlisted Player Y automatically promoted to confirmed entrant; status turns 'approved'.",
     "EntrantPromoter handles waitlist promotion.",
     "Player Y receives push: 'You have been promoted from waitlist to confirmed entrant'."),
    ("TC-CREATOR-124", "Matchday Emergency Lineup Substitution (Injury Before Toss)", "Host Owner (D1)", "Match Center > Lineup",
     "Player twisted ankle in warmups.",
     "1. Tap player on lineup > 'Substitute'.\n2. Pick eligible reserve.\n3. Enter reason.\n4. Save.",
     "Scorecard lineup updates; reserve active; replaced player benched.",
     "Match document records audit log entry with timestamp and official UID.",
     "Immutable record prevents disputed scores."),
    ("TC-CREATOR-125", "Dispute Resolution & Score Correction Sign-Off", "Host Owner (D1)", "Match Result Review",
     "Scoring dispute logged by team captain within 1-hour protest window.",
     "1. Open Protest Review sheet.\n2. Review ball-by-ball video/pad logs.\n3. Adjust final score.\n4. Sign off.",
     "Match status moves from 'provisional' to 'official'; dispute marked resolved.",
     "Leaderboard and Glicko ratings recalculate with corrected score.",
     "Protest window closes permanently.")
]
for item in s1_10: tc(*item)

f.close()
shutil.copy(target, art)
print("Part 1 complete: 125 Creator cases written.")
